version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: portafolicesar
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: porta